# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tags.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TagEditor(object):
    def setupUi(self, TagEditor):
        TagEditor.setObjectName("TagEditor")
        TagEditor.resize(555, 495)
        TagEditor.setMinimumSize(QtCore.QSize(555, 495))
        TagEditor.setMaximumSize(QtCore.QSize(555, 495))
        font = QtGui.QFont()
        font.setPointSize(10)
        TagEditor.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../img/icon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        TagEditor.setWindowIcon(icon)
        TagEditor.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.horizontalLayoutWidget = QtWidgets.QWidget(TagEditor)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(140, 430, 401, 51))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_tags_cancel = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_tags_cancel.setObjectName("pushButton_tags_cancel")
        self.horizontalLayout.addWidget(self.pushButton_tags_cancel)
        self.pushButton_tags_skip = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_tags_skip.setObjectName("pushButton_tags_skip")
        self.horizontalLayout.addWidget(self.pushButton_tags_skip)
        self.pushButton_save = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_save.setObjectName("pushButton_save")
        self.horizontalLayout.addWidget(self.pushButton_save)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(TagEditor)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(140, 60, 401, 41))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_14 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_14.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_2.addWidget(self.label_14)
        self.track_num_0 = QtWidgets.QSpinBox(self.horizontalLayoutWidget_2)
        self.track_num_0.setEnabled(True)
        self.track_num_0.setSpecialValueText("")
        self.track_num_0.setObjectName("track_num_0")
        self.horizontalLayout_2.addWidget(self.track_num_0)
        self.track_num_1 = QtWidgets.QSpinBox(self.horizontalLayoutWidget_2)
        self.track_num_1.setSpecialValueText("")
        self.track_num_1.setObjectName("track_num_1")
        self.horizontalLayout_2.addWidget(self.track_num_1)
        self.label_13 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_13.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_2.addWidget(self.label_13)
        self.disc_num_0 = QtWidgets.QSpinBox(self.horizontalLayoutWidget_2)
        self.disc_num_0.setSpecialValueText("")
        self.disc_num_0.setObjectName("disc_num_0")
        self.horizontalLayout_2.addWidget(self.disc_num_0)
        self.disc_num_1 = QtWidgets.QSpinBox(self.horizontalLayoutWidget_2)
        self.disc_num_1.setSpecialValueText("")
        self.disc_num_1.setObjectName("disc_num_1")
        self.horizontalLayout_2.addWidget(self.disc_num_1)
        self.verticalLayoutWidget = QtWidgets.QWidget(TagEditor)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(140, 110, 401, 311))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout.addWidget(self.lineEdit)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.verticalLayout.addWidget(self.lineEdit_2)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.verticalLayout.addWidget(self.lineEdit_3)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.verticalLayout.addWidget(self.lineEdit_4)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.verticalLayout.addWidget(self.lineEdit_5)
        self.lineEdit_8 = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.verticalLayout.addWidget(self.lineEdit_8)
        self.lineEdit_9 = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.verticalLayout.addWidget(self.lineEdit_9)
        self.lineEdit_10 = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.verticalLayout.addWidget(self.lineEdit_10)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(TagEditor)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(10, 110, 121, 301))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)
        self.label_5 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_2.addWidget(self.label_5)
        self.label_8 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_2.addWidget(self.label_8)
        self.label_9 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_2.addWidget(self.label_9)
        self.label_10 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_10.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_2.addWidget(self.label_10)
        self.lineEdit_name = QtWidgets.QLineEdit(TagEditor)
        self.lineEdit_name.setGeometry(QtCore.QRect(10, 20, 531, 31))
        self.lineEdit_name.setReadOnly(True)
        self.lineEdit_name.setObjectName("lineEdit_name")
        self.label_6 = QtWidgets.QLabel(TagEditor)
        self.label_6.setGeometry(QtCore.QRect(10, 50, 91, 31))
        self.label_6.setObjectName("label_6")

        self.retranslateUi(TagEditor)
        QtCore.QMetaObject.connectSlotsByName(TagEditor)

    def retranslateUi(self, TagEditor):
        _translate = QtCore.QCoreApplication.translate
        TagEditor.setWindowTitle(_translate("TagEditor", "Tags Editor"))
        self.pushButton_tags_cancel.setText(_translate("TagEditor", "Cancel"))
        self.pushButton_tags_skip.setText(_translate("TagEditor", "Skip"))
        self.pushButton_save.setText(_translate("TagEditor", "Save"))
        self.label_14.setText(_translate("TagEditor", "Track"))
        self.label_13.setText(_translate("TagEditor", "Disc"))
        self.label.setText(_translate("TagEditor", "Title"))
        self.label_2.setText(_translate("TagEditor", "Artist"))
        self.label_3.setText(_translate("TagEditor", "Artist URL"))
        self.label_4.setText(_translate("TagEditor", "Album"))
        self.label_5.setText(_translate("TagEditor", "Album Artist"))
        self.label_8.setText(_translate("TagEditor", "Publisher"))
        self.label_9.setText(_translate("TagEditor", "Composer"))
        self.label_10.setText(_translate("TagEditor", "BPM"))
        self.label_6.setText(_translate("TagEditor", "Filename"))
