# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'progressbar_onefile.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ProgressBarOneFileDialog(object):
    def setupUi(self, ProgressBarOneFileDialog):
        ProgressBarOneFileDialog.setObjectName("ProgressBarOneFileDialog")
        ProgressBarOneFileDialog.resize(500, 173)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(ProgressBarOneFileDialog.sizePolicy().hasHeightForWidth())
        ProgressBarOneFileDialog.setSizePolicy(sizePolicy)
        ProgressBarOneFileDialog.setMinimumSize(QtCore.QSize(0, 0))
        ProgressBarOneFileDialog.setMaximumSize(QtCore.QSize(5000, 6000))
        self.gridLayout = QtWidgets.QGridLayout(ProgressBarOneFileDialog)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_ok = QtWidgets.QPushButton(ProgressBarOneFileDialog)
        self.pushButton_ok.setDefault(False)
        self.pushButton_ok.setObjectName("pushButton_ok")
        self.horizontalLayout.addWidget(self.pushButton_ok)
        self.pushButton_abort = QtWidgets.QPushButton(ProgressBarOneFileDialog)
        self.pushButton_abort.setObjectName("pushButton_abort")
        self.horizontalLayout.addWidget(self.pushButton_abort)
        self.gridLayout.addLayout(self.horizontalLayout, 5, 0, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_3 = QtWidgets.QLabel(ProgressBarOneFileDialog)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 0, 0, 1, 1)
        self.progress_text = QtWidgets.QLabel(ProgressBarOneFileDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.progress_text.sizePolicy().hasHeightForWidth())
        self.progress_text.setSizePolicy(sizePolicy)
        self.progress_text.setObjectName("progress_text")
        self.gridLayout_2.addWidget(self.progress_text, 1, 0, 1, 1)
        self.label = QtWidgets.QLabel(ProgressBarOneFileDialog)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 2, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(ProgressBarOneFileDialog)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 3, 0, 1, 1)
        self.label_size = QtWidgets.QLabel(ProgressBarOneFileDialog)
        self.label_size.setObjectName("label_size")
        self.gridLayout_2.addWidget(self.label_size, 0, 1, 1, 1)
        self.label_archiving = QtWidgets.QLabel(ProgressBarOneFileDialog)
        self.label_archiving.setObjectName("label_archiving")
        self.gridLayout_2.addWidget(self.label_archiving, 1, 1, 1, 1)
        self.label_encryption = QtWidgets.QLabel(ProgressBarOneFileDialog)
        self.label_encryption.setObjectName("label_encryption")
        self.gridLayout_2.addWidget(self.label_encryption, 2, 1, 1, 1)
        self.label_deleting = QtWidgets.QLabel(ProgressBarOneFileDialog)
        self.label_deleting.setObjectName("label_deleting")
        self.gridLayout_2.addWidget(self.label_deleting, 3, 1, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_2, 0, 0, 1, 1)

        self.retranslateUi(ProgressBarOneFileDialog)
        QtCore.QMetaObject.connectSlotsByName(ProgressBarOneFileDialog)

    def retranslateUi(self, ProgressBarOneFileDialog):
        _translate = QtCore.QCoreApplication.translate
        ProgressBarOneFileDialog.setWindowTitle(_translate("ProgressBarOneFileDialog", "Progress..."))
        self.pushButton_ok.setText(_translate("ProgressBarOneFileDialog", "OK"))
        self.pushButton_abort.setText(_translate("ProgressBarOneFileDialog", "Abort"))
        self.label_3.setText(_translate("ProgressBarOneFileDialog", "Calculating size..."))
        self.progress_text.setText(_translate("ProgressBarOneFileDialog", "Archiving a folder..."))
        self.label.setText(_translate("ProgressBarOneFileDialog", "Encryption archive..."))
        self.label_2.setText(_translate("ProgressBarOneFileDialog", "Deleting folder..."))
        self.label_size.setText(_translate("ProgressBarOneFileDialog", "Waiting"))
        self.label_archiving.setText(_translate("ProgressBarOneFileDialog", "Waiting"))
        self.label_encryption.setText(_translate("ProgressBarOneFileDialog", "Waiting"))
        self.label_deleting.setText(_translate("ProgressBarOneFileDialog", "Waiting"))
