# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'folderdecrypt.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FolderDecrypt(object):
    def setupUi(self, FolderDecrypt):
        FolderDecrypt.setObjectName("FolderDecrypt")
        FolderDecrypt.resize(587, 99)
        self.gridLayout = QtWidgets.QGridLayout(FolderDecrypt)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.path = QtWidgets.QLabel(FolderDecrypt)
        self.path.setAlignment(QtCore.Qt.AlignCenter)
        self.path.setObjectName("path")
        self.verticalLayout.addWidget(self.path)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.progressBar = QtWidgets.QProgressBar(FolderDecrypt)
        self.progressBar.setEnabled(True)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setTextVisible(True)
        self.progressBar.setObjectName("progressBar")
        self.horizontalLayout.addWidget(self.progressBar)
        self.pushButton_abort = QtWidgets.QPushButton(FolderDecrypt)
        self.pushButton_abort.setObjectName("pushButton_abort")
        self.horizontalLayout.addWidget(self.pushButton_abort)
        self.gridLayout.addLayout(self.horizontalLayout, 3, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 1, 0, 1, 1)

        self.retranslateUi(FolderDecrypt)
        QtCore.QMetaObject.connectSlotsByName(FolderDecrypt)

    def retranslateUi(self, FolderDecrypt):
        _translate = QtCore.QCoreApplication.translate
        FolderDecrypt.setWindowTitle(_translate("FolderDecrypt", "Decrypt in progress..."))
        self.path.setText(_translate("FolderDecrypt", "Path not selected"))
        self.pushButton_abort.setText(_translate("FolderDecrypt", "PushButton"))
