# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'folderencrypt.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FolderEncrypt(object):
    def setupUi(self, FolderEncrypt):
        FolderEncrypt.setObjectName("FolderEncrypt")
        FolderEncrypt.resize(585, 154)
        self.gridLayout = QtWidgets.QGridLayout(FolderEncrypt)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.pushButton_apply = QtWidgets.QPushButton(FolderEncrypt)
        self.pushButton_apply.setObjectName("pushButton_apply")
        self.horizontalLayout_4.addWidget(self.pushButton_apply)
        self.pushButton_cancel = QtWidgets.QPushButton(FolderEncrypt)
        self.pushButton_cancel.setObjectName("pushButton_cancel")
        self.horizontalLayout_4.addWidget(self.pushButton_cancel)
        self.gridLayout.addLayout(self.horizontalLayout_4, 2, 0, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.path = QtWidgets.QLabel(FolderEncrypt)
        self.path.setAlignment(QtCore.Qt.AlignCenter)
        self.path.setObjectName("path")
        self.verticalLayout.addWidget(self.path)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.radioButton_one = QtWidgets.QRadioButton(FolderEncrypt)
        self.radioButton_one.setObjectName("radioButton_one")
        self.horizontalLayout.addWidget(self.radioButton_one)
        self.label = QtWidgets.QLabel(FolderEncrypt)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.radioButton_files = QtWidgets.QRadioButton(FolderEncrypt)
        self.radioButton_files.setChecked(True)
        self.radioButton_files.setObjectName("radioButton_files")
        self.horizontalLayout_3.addWidget(self.radioButton_files)
        self.label_3 = QtWidgets.QLabel(FolderEncrypt)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 1, 0, 1, 1)

        self.retranslateUi(FolderEncrypt)
        QtCore.QMetaObject.connectSlotsByName(FolderEncrypt)

    def retranslateUi(self, FolderEncrypt):
        _translate = QtCore.QCoreApplication.translate
        FolderEncrypt.setWindowTitle(_translate("FolderEncrypt", "Select folder encrypt type"))
        self.pushButton_apply.setText(_translate("FolderEncrypt", "OK"))
        self.pushButton_cancel.setText(_translate("FolderEncrypt", "Cancel"))
        self.path.setText(_translate("FolderEncrypt", "Path not selected"))
        self.radioButton_one.setText(_translate("FolderEncrypt", "One folder-file"))
        self.label.setText(_translate("FolderEncrypt", "Folder to one encrypted file"))
        self.radioButton_files.setText(_translate("FolderEncrypt", "Files"))
        self.label_3.setText(_translate("FolderEncrypt", "Encrypt each unencrypted file in folder"))
