# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qt_designer\progressbar.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ProgressBarDialog(object):
    def setupUi(self, ProgressBarDialog):
        ProgressBarDialog.setObjectName("ProgressBarDialog")
        ProgressBarDialog.resize(700, 112)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(ProgressBarDialog.sizePolicy().hasHeightForWidth())
        ProgressBarDialog.setSizePolicy(sizePolicy)
        ProgressBarDialog.setMinimumSize(QtCore.QSize(500, 112))
        ProgressBarDialog.setMaximumSize(QtCore.QSize(700, 112))
        self.gridLayout = QtWidgets.QGridLayout(ProgressBarDialog)
        self.gridLayout.setObjectName("gridLayout")
        self.progressBar = QtWidgets.QProgressBar(ProgressBarDialog)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.gridLayout.addWidget(self.progressBar, 1, 0, 1, 1)
        self.pushButton_abort = QtWidgets.QDialogButtonBox(ProgressBarDialog)
        self.pushButton_abort.setOrientation(QtCore.Qt.Horizontal)
        self.pushButton_abort.setStandardButtons(QtWidgets.QDialogButtonBox.Abort)
        self.pushButton_abort.setCenterButtons(True)
        self.pushButton_abort.setObjectName("pushButton_abort")
        self.gridLayout.addWidget(self.pushButton_abort, 2, 0, 1, 1)
        self.progress_text = QtWidgets.QLabel(ProgressBarDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.progress_text.sizePolicy().hasHeightForWidth())
        self.progress_text.setSizePolicy(sizePolicy)
        self.progress_text.setObjectName("progress_text")
        self.gridLayout.addWidget(self.progress_text, 0, 0, 1, 1)

        self.retranslateUi(ProgressBarDialog)
        self.pushButton_abort.accepted.connect(ProgressBarDialog.accept) # type: ignore
        self.pushButton_abort.rejected.connect(ProgressBarDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(ProgressBarDialog)

    def retranslateUi(self, ProgressBarDialog):
        _translate = QtCore.QCoreApplication.translate
        ProgressBarDialog.setWindowTitle(_translate("ProgressBarDialog", "Progress..."))
        self.progress_text.setText(_translate("ProgressBarDialog", "Initialization..."))
