# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qt_designer\settings.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SettingsDialog(object):
    def setupUi(self, SettingsDialog):
        SettingsDialog.setObjectName("SettingsDialog")
        SettingsDialog.resize(492, 326)
        font = QtGui.QFont()
        font.setPointSize(10)
        SettingsDialog.setFont(font)
        SettingsDialog.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(SettingsDialog)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(SettingsDialog)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.line = QtWidgets.QFrame(SettingsDialog)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_2.addWidget(self.line)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.targetPath = QtWidgets.QLineEdit(SettingsDialog)
        self.targetPath.setObjectName("targetPath")
        self.gridLayout.addWidget(self.targetPath, 2, 2, 1, 1)
        self.enableCopyToTarget = QtWidgets.QCheckBox(SettingsDialog)
        self.enableCopyToTarget.setObjectName("enableCopyToTarget")
        self.gridLayout.addWidget(self.enableCopyToTarget, 0, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(SettingsDialog)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 2, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        self.line_2 = QtWidgets.QFrame(SettingsDialog)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_2.addWidget(self.line_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.showCoords = QtWidgets.QCheckBox(SettingsDialog)
        self.showCoords.setObjectName("showCoords")
        self.horizontalLayout.addWidget(self.showCoords)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.pushButton_apply = QtWidgets.QPushButton(SettingsDialog)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_apply.setFont(font)
        self.pushButton_apply.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.pushButton_apply.setObjectName("pushButton_apply")
        self.gridLayout_2.addWidget(self.pushButton_apply, 0, 2, 1, 1)
        self.pushButton_cancel = QtWidgets.QPushButton(SettingsDialog)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_cancel.setFont(font)
        self.pushButton_cancel.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.pushButton_cancel.setObjectName("pushButton_cancel")
        self.gridLayout_2.addWidget(self.pushButton_cancel, 0, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 0, 0, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_2)

        self.retranslateUi(SettingsDialog)
        QtCore.QMetaObject.connectSlotsByName(SettingsDialog)

    def retranslateUi(self, SettingsDialog):
        _translate = QtCore.QCoreApplication.translate
        SettingsDialog.setWindowTitle(_translate("SettingsDialog", "Settings"))
        self.label_2.setText(_translate("SettingsDialog", "Settings"))
        self.enableCopyToTarget.setText(_translate("SettingsDialog", "Enable copy to target button"))
        self.label_3.setText(_translate("SettingsDialog", "Copy traget"))
        self.showCoords.setText(_translate("SettingsDialog", "Show pixel coordiantes"))
        self.pushButton_apply.setText(_translate("SettingsDialog", "Apply"))
        self.pushButton_cancel.setText(_translate("SettingsDialog", "Cancel"))
