import os
import sys
import datetime
import traceback

import Crypto
import PIL

from PyQt5 import QtWidgets
from PyQt5.QtCore import QT_VERSION_STR, PYQT_VERSION_STR

from src.gui.window_app import MainWindow

__version__ = "3.0.4"


def except_hook(exc_type, exc_value, exc_tb):
    ex_text = "This crash file generated by SecurePhotos\n"
    ex_text += "Please send this file to mail: annndruha.github@gmail.com\n"
    ex_text += "Or create issue on https://github.com/annndruha/SecurePhotos/issues\n\n"
    ex_text += f"==SecurePhotos: {__version__}\n"
    ex_text += f"==Python: {sys.version}\n"
    ex_text += f"==Crypto: {Crypto.__version__}\n"
    ex_text += f"==PIL: {PIL.__version__}\n"
    ex_text += f"==PyQt5: {PYQT_VERSION_STR}\n"
    ex_text += f"==Qt: {QT_VERSION_STR}\n\n"
    ex_text += ''.join(traceback.format_exception(exc_type, exc_value, exc_tb))
    print(ex_text)

    cur_path = os.path.dirname(sys.executable)
    filename = f"Crash_SecurePhotos_{datetime.datetime.now().strftime('%Y_%m_%d_%H_%M_%S')}.txt"
    with open(os.path.join(cur_path, filename), "w+", encoding='utf-8') as f:
        f.write(ex_text)
    QtWidgets.QApplication.quit()


if __name__ == '__main__':
    sys.excepthook = except_hook
    app = QtWidgets.QApplication(sys.argv)
    application = MainWindow(__version__)
    application.show()
    app.exec()
