import datetime
import os
import sys
import traceback

from PyQt5 import QtWidgets

from src.gui.window_app import MainWindow
from src.utils.about import About


def except_hook(exc_type, exc_value, exc_tb):
    ex_text = "This crash file generated by SecurePhotos\n"
    ex_text += "Create issue on https://github.com/annndruha/SecurePhotos/issues\n\n"
    ex_text += "or send this file to autor e-mail: annndruha.github@gmail.com\n\n"
    ex_text += '\n=='.join(About().versions) + "\n"
    ex_text += ''.join(traceback.format_exception(exc_type, exc_value, exc_tb))
    print(ex_text)

    cur_path = os.path.dirname(sys.executable)
    filename = f"Crash_SecurePhotos_{datetime.datetime.now().strftime('%Y_%m_%d_%H_%M_%S')}.txt"
    with open(os.path.join(cur_path, filename), "w+", encoding='utf-8') as f:
        f.write(ex_text)
    QtWidgets.QApplication.quit()


if __name__ == '__main__':
    sys.excepthook = except_hook
    app = QtWidgets.QApplication(sys.argv)
    application = MainWindow(About().__version__)
    application.show()
    app.exec()
