name: Windows Build by Pyinstaller

on:
  create:
    tags:
      - v*

jobs:
  build:

    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: install_requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r dev-requirements.txt

      - name: Build Windows executable
        run: ./build.bat

      - uses: actions/upload-artifact@v4
        with:
          name: SecurePhotos-windows.zip
          path: SecurePhotos.exe