name: whl package

on:
  create:
    tags:
      - v*

jobs:
  build:

    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: install_requirements
        run: |
          python -m pip install --upgrade pip build

      - name: Build Windows executable
        run: python3 -m build

      - uses: actions/upload-artifact@v4
        with:
          name: python-wheel.zip
          path: dist
